export const FETCH_PLANETS_REQUESTED = "FETCH_PLANETS_REQUESTED";
export const FETCH_PLANETS_SUCCESS = "FETCH_PLANETS_SUCCESS";
export const FETCH_PLANETS_FAILURE = "FETCH_PLANETS_FAILURE";

export const FETCH_PLANET_INFO_REQUESTED = "FETCH_PLANET_INFO_REQUESTED";
export const FETCH_PLANET_INFO_SUCCESS = "FETCH_PLANET_INFO_SUCCESS";
export const FETCH_PLANET_INFO_FAILURE = "FETCH_PLANET_INFO_FAILURE";

export const FETCH_PERSON_INFO_REQUESTED = "FETCH_PERSON_INFO_REQUESTED";
export const FETCH_PERSON_INFO_SUCCESS = "FETCH_PERSON_INFO_SUCCESS";
export const FETCH_PERSON_INFO_FAILURE = "FETCH_PERSON_INFO_FAILURE";
